name: aos-adjutant
services:
  webapp:
    image: ghcr.io/dhunsel/aos-adjutant/webapp:${WEBAPP_VERSION}
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT: Production
      - Authentication__ClientId: ${CLIENT_ID}
      - Authentication__ClientSecret: ${CLIENT_SECRET}
      - Authentication__Authority: ${AUTH_URL}
      - DbContextConnectionString: ${DB_CONNECTION_STRING}
      - AllowedHosts: ${HOSTNAME}
    logging:
      driver: local
    depends_on:
      postgres:
        condition: service_healthy
      pocket-id:
        condition: service_healthy
    networks:
      - private
      - proxy

  postgres:
    image: postgres:18.1
    restart: unless-stopped
    environment:
      - POSTGRES_DB: aos_adjutant
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - MIGRATOR_PASSWORD: ${MIGRATOR_PASSWORD}
      - APP_PASSWORD: ${APP_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    logging:
      driver: local
    healthcheck:
      test: [ "CMD", "pg_isready -U postgres -d aos_adjutant" ]
      interval: 10s
      timeout: 5s
      retries: 3
    shm_size: 256mb
    networks:
      - private

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2
    restart: unless-stopped
    environment:
      - APP_URL: ${AUTH_URL}
      - ENCRYPTION_KEY: ${AUTH_ENCRYPTION_KEY}
      - TRUS_PROXY: ${AUTH_TRUST_PROXY}
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck"]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    volumes:
      - pocket-id-data:/app/data
    logging:
      driver: local
    networks:
      - proxy

  grafana:
    image: grafana/grafana:12.4
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./observability/grafana/provisioning/:/etc/grafana/provisioning:ro
    logging:
      driver: local
    networks:
      - private
      - proxy

  loki:
    image: grafana/loki:3
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - 3100:3100
    volumes:
      - ./observability/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki-data:/loki
    logging:
      driver: local
    networks:
      - private

  prometheus:
    image: prom/prometheus:v3
    command:
      - --web.enable-otlp-receiver
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    volumes:
      - ./observability/prometheus/:/etc/prometheus:ro
      - prometheus-data:/prometheus
    logging:
      driver: local
    networks:
      - private

  tempo:
    image: grafana/tempo:2.4.0
    command: "-config.file=/etc/tempo.yaml"
    volumes:
      - ./observability/tempo/tempo.yaml:/etc/tempo.yaml:ro
      - tempo-data:/var/tempo
    ports:
      - 3200:3200
      - 4317:4317
      - 4318:4318
    logging:
      driver: local
    networks:
      - private

volumes:
  postgres-data:
  loki-data:
  prometheus-data:
  grafana-data:
  tempo-data:
  pocket-id-data:

networks:
  private:
    internal: true
  proxy:

