CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE TABLE "user" (
        user_id integer GENERATED BY DEFAULT AS IDENTITY,
        public_id uuid NOT NULL,
        username character varying(250) NOT NULL,
        email character varying(250) NOT NULL,
        identity_provider character varying(250) NOT NULL,
        subject character varying(250) NOT NULL,
        CONSTRAINT "PK_user" PRIMARY KEY (user_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE TABLE weapon_effect (
        weapon_effect_id integer GENERATED BY DEFAULT AS IDENTITY,
        key character varying(250) NOT NULL,
        name character varying(250) NOT NULL,
        CONSTRAINT "PK_weapon_effect" PRIMARY KEY (weapon_effect_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE TABLE ability (
        ability_id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(250) NOT NULL,
        reaction character varying(250),
        declaration character varying(250),
        effect character varying(250) NOT NULL,
        phase character varying(250) NOT NULL,
        restriction character varying(250),
        turn character varying(250),
        is_generic boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        created_by_user_id integer,
        modified_at timestamp with time zone,
        modified_by_user_id integer,
        CONSTRAINT "PK_ability" PRIMARY KEY (ability_id),
        CONSTRAINT "FK_ability_user_created_by_user_id" FOREIGN KEY (created_by_user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_ability_user_modified_by_user_id" FOREIGN KEY (modified_by_user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE TABLE faction (
        faction_id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(250) NOT NULL,
        grand_alliance character varying(250) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        created_by_user_id integer,
        modified_at timestamp with time zone,
        modified_by_user_id integer,
        CONSTRAINT "PK_faction" PRIMARY KEY (faction_id),
        CONSTRAINT "FK_faction_user_created_by_user_id" FOREIGN KEY (created_by_user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_faction_user_modified_by_user_id" FOREIGN KEY (modified_by_user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE TABLE battle_formation (
        battle_formation_id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(250) NOT NULL,
        faction_id integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        created_by_user_id integer,
        modified_at timestamp with time zone,
        modified_by_user_id integer,
        CONSTRAINT "PK_battle_formation" PRIMARY KEY (battle_formation_id),
        CONSTRAINT "FK_battle_formation_faction_faction_id" FOREIGN KEY (faction_id) REFERENCES faction (faction_id) ON DELETE CASCADE,
        CONSTRAINT "FK_battle_formation_user_created_by_user_id" FOREIGN KEY (created_by_user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_battle_formation_user_modified_by_user_id" FOREIGN KEY (modified_by_user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE TABLE faction_ability (
        ability_id integer NOT NULL,
        faction_id integer NOT NULL,
        CONSTRAINT "PK_faction_ability" PRIMARY KEY (ability_id, faction_id),
        CONSTRAINT "FK_faction_ability_ability_ability_id" FOREIGN KEY (ability_id) REFERENCES ability (ability_id) ON DELETE CASCADE,
        CONSTRAINT "FK_faction_ability_faction_faction_id" FOREIGN KEY (faction_id) REFERENCES faction (faction_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE TABLE unit (
        unit_id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(250) NOT NULL,
        health integer NOT NULL,
        move character varying(250) NOT NULL,
        save integer NOT NULL,
        control integer NOT NULL,
        ward_save integer,
        faction_id integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        created_by_user_id integer,
        modified_at timestamp with time zone,
        modified_by_user_id integer,
        CONSTRAINT "PK_unit" PRIMARY KEY (unit_id),
        CONSTRAINT "FK_unit_faction_faction_id" FOREIGN KEY (faction_id) REFERENCES faction (faction_id) ON DELETE CASCADE,
        CONSTRAINT "FK_unit_user_created_by_user_id" FOREIGN KEY (created_by_user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_unit_user_modified_by_user_id" FOREIGN KEY (modified_by_user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE TABLE battle_formation_ability (
        ability_id integer NOT NULL,
        battle_formation_id integer NOT NULL,
        CONSTRAINT "PK_battle_formation_ability" PRIMARY KEY (ability_id, battle_formation_id),
        CONSTRAINT "FK_battle_formation_ability_ability_ability_id" FOREIGN KEY (ability_id) REFERENCES ability (ability_id) ON DELETE CASCADE,
        CONSTRAINT "FK_battle_formation_ability_battle_formation_battle_formation_~" FOREIGN KEY (battle_formation_id) REFERENCES battle_formation (battle_formation_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE TABLE attack_profile (
        attack_profile_id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(250) NOT NULL,
        is_ranged boolean NOT NULL,
        range integer,
        attacks character varying(250) NOT NULL,
        to_hit integer NOT NULL,
        to_wound integer NOT NULL,
        rend integer,
        damage character varying(250) NOT NULL,
        unit_id integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        created_by_user_id integer,
        modified_at timestamp with time zone,
        modified_by_user_id integer,
        CONSTRAINT "PK_attack_profile" PRIMARY KEY (attack_profile_id),
        CONSTRAINT "FK_attack_profile_unit_unit_id" FOREIGN KEY (unit_id) REFERENCES unit (unit_id) ON DELETE CASCADE,
        CONSTRAINT "FK_attack_profile_user_created_by_user_id" FOREIGN KEY (created_by_user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_attack_profile_user_modified_by_user_id" FOREIGN KEY (modified_by_user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE TABLE unit_ability (
        ability_id integer NOT NULL,
        unit_id integer NOT NULL,
        CONSTRAINT "PK_unit_ability" PRIMARY KEY (ability_id, unit_id),
        CONSTRAINT "FK_unit_ability_ability_ability_id" FOREIGN KEY (ability_id) REFERENCES ability (ability_id) ON DELETE CASCADE,
        CONSTRAINT "FK_unit_ability_unit_unit_id" FOREIGN KEY (unit_id) REFERENCES unit (unit_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE TABLE attack_profile_weapon_effect (
        attack_profile_id integer NOT NULL,
        weapon_effect_id integer NOT NULL,
        CONSTRAINT "PK_attack_profile_weapon_effect" PRIMARY KEY (attack_profile_id, weapon_effect_id),
        CONSTRAINT "FK_attack_profile_weapon_effect_attack_profile_attack_profile_~" FOREIGN KEY (attack_profile_id) REFERENCES attack_profile (attack_profile_id) ON DELETE CASCADE,
        CONSTRAINT "FK_attack_profile_weapon_effect_weapon_effect_weapon_effect_id" FOREIGN KEY (weapon_effect_id) REFERENCES weapon_effect (weapon_effect_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    INSERT INTO weapon_effect (weapon_effect_id, key, name)
    VALUES (1, 'crit_2_hits', 'Crit (2 Hits)');
    INSERT INTO weapon_effect (weapon_effect_id, key, name)
    VALUES (2, 'crit_auto_wound', 'Crit (Auto-wound)');
    INSERT INTO weapon_effect (weapon_effect_id, key, name)
    VALUES (3, 'crit_mortal', 'Crit (Mortal)');
    INSERT INTO weapon_effect (weapon_effect_id, key, name)
    VALUES (4, 'charge_1_damage', 'Charge (+1 Damage)');
    INSERT INTO weapon_effect (weapon_effect_id, key, name)
    VALUES (5, 'companion', 'Companion');
    INSERT INTO weapon_effect (weapon_effect_id, key, name)
    VALUES (6, 'shoot_in_combat', 'Shoot in Combat');
    INSERT INTO weapon_effect (weapon_effect_id, key, name)
    VALUES (7, 'anti_monster', 'Anti-Monster (+1 Rend)');
    INSERT INTO weapon_effect (weapon_effect_id, key, name)
    VALUES (8, 'anti_hero', 'Anti-Hero (+1 Rend)');
    INSERT INTO weapon_effect (weapon_effect_id, key, name)
    VALUES (9, 'anti_infantry', 'Anti-Infantry (+1 Rend)');
    INSERT INTO weapon_effect (weapon_effect_id, key, name)
    VALUES (10, 'anti_cavalry', 'Anti-Cavalry (+1 Rend)');
    INSERT INTO weapon_effect (weapon_effect_id, key, name)
    VALUES (11, 'anti_wizard', 'Anti-Wizard (+1 Rend)');
    INSERT INTO weapon_effect (weapon_effect_id, key, name)
    VALUES (12, 'anti_manifestation', 'Anti-Manifestation (+1 Rend)');
    INSERT INTO weapon_effect (weapon_effect_id, key, name)
    VALUES (13, 'anti_charge', 'Anti-Charge (+1 Rend)');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_ability_created_by_user_id" ON ability (created_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_ability_modified_by_user_id" ON ability (modified_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_attack_profile_created_by_user_id" ON attack_profile (created_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_attack_profile_modified_by_user_id" ON attack_profile (modified_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_attack_profile_name_unit_id" ON attack_profile (name, unit_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_attack_profile_unit_id" ON attack_profile (unit_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_attack_profile_weapon_effect_weapon_effect_id" ON attack_profile_weapon_effect (weapon_effect_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_battle_formation_created_by_user_id" ON battle_formation (created_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_battle_formation_faction_id_name" ON battle_formation (faction_id, name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_battle_formation_modified_by_user_id" ON battle_formation (modified_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_battle_formation_ability_ability_id" ON battle_formation_ability (ability_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_battle_formation_ability_battle_formation_id" ON battle_formation_ability (battle_formation_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_faction_created_by_user_id" ON faction (created_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_faction_modified_by_user_id" ON faction (modified_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_faction_name" ON faction (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_faction_ability_ability_id" ON faction_ability (ability_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_faction_ability_faction_id" ON faction_ability (faction_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_unit_created_by_user_id" ON unit (created_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_unit_faction_id_name" ON unit (faction_id, name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_unit_modified_by_user_id" ON unit (modified_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_unit_ability_ability_id" ON unit_ability (ability_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE INDEX "IX_unit_ability_unit_id" ON unit_ability (unit_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_user_identity_provider_subject" ON "user" (identity_provider, subject);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_user_public_id" ON "user" (public_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_weapon_effect_key" ON weapon_effect (key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_weapon_effect_name" ON weapon_effect (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('weapon_effect', 'weapon_effect_id'),
        GREATEST(
            (SELECT MAX(weapon_effect_id) FROM weapon_effect) + 1,
            nextval(pg_get_serial_sequence('weapon_effect', 'weapon_effect_id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531160905_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260531160905_InitialCreate', '10.0.7');
    END IF;
END $EF$;
COMMIT;

